# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: nginx
#   namespace: default
# spec:
#   releaseName: nginx
#   chart:
#     spec:
#       chart: ./nginx-chart
#   interval: 5m
#   values:
#     image:
#       repository: nginx
#       tag: "1.21.0"
#     service:
#       type: LoadBalancer


apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sandbox
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: ./nginx-chart
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: sandbox
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2
