apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  releaseName: nginx
  chart:
    spec:
      chart: ./nginx-chart
  interval: 5m
  values:
    image:
      repository: nginx
      tag: "1.21.0"
    service:
      type: LoadBalancer
